channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=22.2.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==1.24.4
  - pandas==2.2.3
  - scikit-learn==1.6.1
  - scipy==1.15.3
  - xgboost==3.0.1
name: mlflow-env
